// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Get Started"
          text="Ready to enhance the security and safety of your organization? Contact DLJ Protection today for a comprehensive security consultation."
          primaryButton={{
            text: "Schedule a Consultation",
            href: "#",
          }}
          secondaryButton={{
            text: "Email Our Team",
            href: "mailto:info@dljprotection.com",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
