// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Support"
          title="Frequently Asked Questions"
          description="Understand how DLJ Protection prioritizes your safety and communication needs."
          categories={[
            {
              name: "General Services",
              items: [
                {
                  question: "What is the difference between patrol and on-site guards?",
                  answer: "On-site guards provide constant presence at a specific location, while patrol services provide random, visible deterrents across larger or multiple areas.",
                },
                {
                  question: "Are your security personnel trained?",
                  answer: "Yes, our team undergoes rigorous training focusing on communication, professionalism, and preparedness.",
                },
              ],
            },
            {
              name: "Partnerships",
              items: [
                {
                  question: "Can we get custom security protocols?",
                  answer: "Absolutely. We pride ourselves on creating security programs built around the unique requirements and challenges of your specific property or business.",
                },
              ],
            },
          ]}
          cta={{
            name: "Need a Consultation?",
            role: "Speak to our team today",
            buttonText: "Contact DLJ Protection",
            buttonHref: "#contact",
            imageSrc: "http://img.b2bpic.net/free-photo/young-man-black-shirt-with-cap-holding-gift-box-looking-cheerful_176474-11304.jpg",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
