// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitMediaGrid from '@/components/sections/hero/HeroSplitMediaGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitMediaGrid
        tag="Veteran-Owned & Operated"
        title="Security You Can Trust. Protection You Can Count On."
        description="DLJ Protection delivers dependable, professional security solutions designed around the specific needs of your business, property, or community. Veteran leadership, human-centered vigilance."
        primaryButton={{
            text: "Request a Security Consultation",
            href: "#contact",
          }}
        secondaryButton={{
            text: "Explore Our Services",
            href: "#services",
          }}
        items={[{"imageSrc":"https://images.unsplash.com/photo-1582139329536-e7284fece509?auto=format&fit=crop&w=800&q=80"},{"imageSrc":"https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80"}]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
