// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesBentoGrid
          tag="Comprehensive Protection"
          title="Tailored Security Services"
          description="Customized security programs designed for your specific environment, ensuring peace of mind for employees, residents, and stakeholders."
          features={[
            {
              title: "Security Guard Services",
              description: "Professional on-site security personnel for businesses, properties, and organizations.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-airport-security-officer-holding-metal-detector-airport-terminal_107420-95848.jpg",
            },
            {
              title: "Patrol Services",
              description: "Visible and consistent patrols designed to deter unwanted activity and identify potential issues.",
              imageSrc: "http://img.b2bpic.net/free-photo/side-view-valet-parking-man-s-car_23-2149901435.jpg",
            },
            {
              title: "Construction Site Security",
              description: "Specialized solutions to protect equipment, materials, and property perimeters.",
              imageSrc: "http://img.b2bpic.net/free-photo/robot-working-construction_1048-1764.jpg",
            },
            {
              title: "Commercial Property Security",
              description: "Reliable security for offices, retail, warehouses, and complex commercial environments.",
              imageSrc: "http://img.b2bpic.net/free-photo/business-people-entering-office-building_107420-74364.jpg",
            },
          ]}
          primaryButton={{
            text: "Request Consultation",
            href: "#contact",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
