// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamOverlayCards from '@/components/sections/team/TeamOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
        <SectionErrorBoundary name="team">
              <TeamOverlayCards
          tag="Our Leadership"
          title="Veteran-Led Accountability"
          description="Our team brings military-grade discipline and a human-centered approach to every engagement, ensuring we always operate with respect and excellence."
          members={[
            {
              name: "Marcus Thorne",
              role: "Director of Operations",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-businessman-smiling_23-2147985511.jpg",
            },
            {
              name: "Elena Rodriguez",
              role: "Client Relations Manager",
              imageSrc: "http://img.b2bpic.net/free-photo/attractive-male-cop-with-ammunition-holding-gun-with-both-hands-front-view-bearded-man-black_7502-10633.jpg",
            },
            {
              name: "David Chen",
              role: "Security Compliance Lead",
              imageSrc: "http://img.b2bpic.net/free-photo/young-man-holding-mini-notebook-black-shirt-cap_176474-11287.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
