/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import GridOrCarousel from "@/components/ui/GridOrCarousel";
import ScrollReveal from "@/components/ui/ScrollReveal";

const members = [
  {
    name: "Donte Sanders",
    role: "Founder & CEO / DLJ Owner",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3HymNublRvuFtoKZ5cOUF2ujXj0/uploaded-1786850139072-spnpazqf.jpg"
  },
  {
    name: "Jontrell Taylor",
    role: "Director of Security",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3HymNublRvuFtoKZ5cOUF2ujXj0/uploaded-1787159565437-caenv4d4.jpg"
  },
  {
    name: "D. Mattox",
    role: "Client Relations Manager",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3HymNublRvuFtoKZ5cOUF2ujXj0/uploaded-1786909392908-mpau08jp.png"
  }
];

type TeamMember = {
  name: string;
  role: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const TeamInline = () => (
  <section aria-label="Team section" className="py-20">
    <div className="flex flex-col gap-8 md:gap-10">
      <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Our Leadership"}</p>
        </div>

        <TextAnimation
          text={"Veteran-Led Accountability"}
          variant={"slide-up"}
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Our team brings military-grade discipline and a human-centered approach to every engagement, ensuring we always operate with respect and excellence."}
          variant={"slide-up"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
          </div>
        )}
      </div>

      <ScrollReveal variant="slide-up">
        <GridOrCarousel >
          {members.map((member) => (
            <div key={member.name} className="relative aspect-4/5 card rounded">
              <div className="relative w-full h-full rounded overflow-hidden">
                <ImageOrVideo imageSrc={member.imageSrc} videoSrc={member.videoSrc} />

                <div className="absolute inset-x-4 bottom-4 xl:inset-x-5 xl:bottom-5 2xl:inset-x-6 2xl:bottom-6 flex items-center justify-between gap-4 xl:gap-5 2xl:gap-6 p-4 xl:p-5 2xl:p-6 card backdrop-blur-sm rounded">
                  <span className="text-xl font-semibold leading-snug truncate">{member.name}</span>
                  <div className="px-3 py-2 text-sm primary-button text-primary-cta-text rounded">
                    <p className="truncate">{member.role}</p>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </GridOrCarousel>
      </ScrollReveal>
    </div>
  </section>
);

export default function TeamSection() {
  return (
    <div data-webild-section="team" data-section="team" id="team">
      <TeamInline />
    </div>
  );
}
