// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeOverlayCards from '@/components/sections/testimonial/TestimonialMarqueeOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeOverlayCards
          tag="Client Trust"
          title="What Our Partners Say"
          description="We are proud to serve communities and businesses that value professionalism and reliable security."
          testimonials={[
            {
              name: "Sarah Miller",
              role: "Property Manager",
              company: "Highview Commercial",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-people-working-from-home_23-2149173331.jpg",
            },
            {
              name: "James Anderson",
              role: "Site Lead",
              company: "Summit Construction",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/asian-construction-firm-executive-business-suit-safety-vest-sitting-office_1098-17514.jpg",
            },
            {
              name: "Linda Wu",
              role: "Director",
              company: "Urban Residential",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/low-angle-smiley-business-woman_23-2148356286.jpg",
            },
            {
              name: "Michael Reed",
              role: "Operations VP",
              company: "Northstar Logistics",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiling-businessman-sitting-desk-table-business-company-office_482257-16773.jpg",
            },
            {
              name: "Jessica Patel",
              role: "Facilities Mgr",
              company: "Grand Center",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-interviewee-taking-notes_23-2149037865.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
