// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "trust" section.

import React from 'react';
import AboutTestimonial from '@/components/sections/about/AboutTestimonial';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TrustSection(): React.JSX.Element {
  return (
    <div id="trust" data-section="trust">
        <SectionErrorBoundary name="trust">
              <AboutTestimonial
          tag="Our Core Values"
          quote="Our commitment is defined by unwavering professionalism, reliability, and vigilance. We provide responsive security that respects the people and environments we are trusted to protect."
          author="The DLJ Protection Leadership"
          role="Veteran-Led Security Excellence"
          textAnimation="slide-up"
          imageSrc="https://storage.googleapis.com/webild/users/user_3HymNublRvuFtoKZ5cOUF2ujXj0/uploaded-1786907592716-628y5o8n.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
