/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { Quote } from "lucide-react";
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";

type AboutTestimonialProps = {
  tag: string;
  quote: string;
  author: string;
  role: string;
  textAnimation: "slide-up" | "fade-blur" | "fade";
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const TrustInline = () => {
  return (
    <section aria-label="Trust and Mission" className="py-20">
      <div className="relative mx-auto w-content-width min-h-[480px] card rounded overflow-hidden p-8 md:p-16 flex flex-col justify-end">
        <div className="absolute inset-0 z-0">
          <img
            src="https://storage.googleapis.com/webild/users/user_3HymNublRvuFtoKZ5cOUF2ujXj0/uploaded-1786907592715-gifkbyl7.png"
            alt="DLJ Protection Veteran Leadership"
            className="w-full h-full object-cover object-top"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/65 to-black/30" />
        </div>

        <div className="absolute flex items-center justify-center top-6 left-6 md:top-8 md:left-8 size-14 md:size-16 primary-button rounded z-10 overflow-hidden p-2">
          <img
            src="https://storage.googleapis.com/webild/users/user_3HymNublRvuFtoKZ5cOUF2ujXj0/uploaded-1786907592715-gifkbyl7.png"
            alt="DLJ Protection Shield Logo"
            className="w-full h-full object-contain"
          />
        </div>

        <div className="relative z-10 flex flex-col justify-end gap-5 max-w-3xl mt-16">
          <div className="w-fit px-3 py-1 text-sm bg-white/10 backdrop-blur-md text-white border border-white/20 rounded font-medium">
            <p>{"Veteran-Owned & Operated"}</p>
          </div>

          <TextAnimation
            text={"DLJ Protection is proudly veteran-owned and operated. We are partnered with Swords to Plowshares, reserving a percentage of our workforce for military veterans."}
            variant={"slide-up"}
            gradientText={false}
            tag="h2"
            className="text-3xl md:text-5xl leading-[1.15] font-semibold text-white text-balance"
          />

          <div className="flex flex-wrap items-center gap-2 md:gap-3 text-sm md:text-base font-medium text-white/90 pt-2">
            <span>{"Swords to Plowshares Partner"}</span>
            <span className="text-white/40">•</span>
            <span>{"Veteran Workforce Program"}</span>
            <span className="text-white/40">•</span>
            <span>{"Veteran-Led Security Excellence"}</span>
          </div>
        </div>
      </div>
    </section>
  );
};

export default function TrustSection() {
  return (
    <div data-webild-section="trust" data-section="trust" id="trust">
      <TrustInline />
    </div>
  );
}
